version: '3.3'
services:
  mongo:
    container_name: mongo
    ports:
      - '27888:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    image: mongo
  node:
    container_name: node
    ports:
      - '4200:3000'
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongoadmin:secret@mongo:27017/jsonschemadiscovery?authSource=admin
